### ISSUE TITLE
Go to the end of the road

### ISSUE THREAD

**Issue by pesehr** [1995parham/RoadToMSc#19]
What happend? Why are you stopping?

**Comment by pesehr** [comment]
"Winners lose more than losers. They win and lose more than losers because they stay in the game."
Stay in the game bro

**Comment by behroozfarkiani** [comment]
Basic Philosophy of doing a master is to go a bit deeper in science and learn how to define and solve a "small" real-world problem by applying abstraction on different levels. You are going to learn how to manage your time budget and how to handle different aspects of the problem. 
Good to know, Every engineering problem involves doing some maths/physics/chemistry whether you like it or not, but as far as I can remember, your thesis doesn't have any math at all. The little formal description of your problem or other people problems is not math or doing math! It is a way to speak clearly so everyone can understand what you are trying to say. What is your problem and are you trying to solve a problem that is already solved by other people? 
It is better to ask yourself "What is the difference between me and a bachelor student? Am I ready to solve a small real-world problem? Do I able to abstract and simplify a real-world problem? Can I manage my time budget? " If you miss any of these questions, so yes, you are loosing and your not ready to be awarded a master degree. 
The only question remained is what is a good problem? Actually, I prefer the hardest "real" ones because I can learn a lot. Everyone can make their choice and you made that. To me, your problems are easy to solve and implement but @1995parham and @pesehr haven't spent enough time on them. No pain, no gain.
